line-length = 79
target-version = "py312"

exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
    "*/config",
    "*/migrations",
    "manage.py",
]

