# Generated by Django 6.0.6 on 2026-06-07 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('score', models.JSONField(verbose_name='Score')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tennis_match_scoreboard.players', verbose_name='Player1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tennis_match_scoreboard.players', verbose_name='Player2')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_match_scoreboard.players', verbose_name='Winner')),
            ],
            options={
                'db_table': 'Matches',
                'constraints': [models.CheckConstraint(condition=models.Q(('player1', models.F('player2')), _negated=True), name='player1_not_player2'), models.CheckConstraint(condition=models.Q(('winner', models.F('player1')), ('winner', models.F('player2')), _connector='OR'), name='winner_must_be_player1_or_player2')],
            },
        ),
    ]
