events {
    worker_connections 1024;
}

http{

    upstream tennis_match_scoreboard {
        server tennis_match_scoreboard:8000;
    }

    server {

        listen 80;

        charset utf-8;

        location /static {
            root /;
            types {
                text/css css;
                application/javascript js;
                image/png png;
            }
        }

        location / {
            proxy_pass http://tennis_match_scoreboard;
            proxy_set_header Host $host;
        }


    }
}