name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install project dependencies
        run: uv sync --frozen

      - name: run Ruff linter
        run:
          uv run ruff check . --show-files

      - name: run Ruff formatter
        run:
          uv run ruff format

      - name: Run MyPy
        run:
          uv run mypy .

      - name: Run Typos
        run:
          uv run typos

      - name: Run pytest
        run:
          uv run pytest .
